2020-08-06 18:27:17 [INFO] config: Config(feed=FeedConfig(base_url='https://release-feeds.zhimingwang.org/', author='release-feeds', aggregate_title='Aggregate software releases'), packages=['ffmpeg', 'golang-defaults', 'pandoc', 'python3-defaults', 'rustc', 'zsh'])
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/ffmpeg/
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/python3-defaults/
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/pandoc/
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/rustc/
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/zsh/
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/rustc/1.45.0+dfsg1-1/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/python3-defaults/3.8.2-3/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/pandoc/2.9.1.1-3/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/zsh/5.8-5/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/api/src/ffmpeg/7:4.3.1-1/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/data/main/p/python3-defaults/3.8.2-3/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/data/main/p/pandoc/2.9.1.1-3/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/data/main/z/zsh/5.8-5/debian/watch
2020-08-06 18:27:17 [INFO] GET https://sources.debian.org/data/main/f/ffmpeg/7:4.3.1-1/debian/watch
2020-08-06 18:27:18 [INFO] GET https://sources.debian.org/data/main/r/rustc/1.45.0+dfsg1-1/debian/watch
2020-08-06 18:27:18 [INFO] python3-defaults 3.8.5: https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tar.xz
2020-08-06 18:27:19 [INFO] golang-defaults 1.14.7: https://golang.org/dl/go1.14.7.src.tar.gz
2020-08-06 18:27:19 [INFO] rustc 1.45.2: https://static.rust-lang.org/dist/rustc-1.45.2-src.tar.xz
2020-08-06 18:27:19 [INFO] pandoc 2.10.1: https://hackage.haskell.org/package/pandoc-2.10.1/pandoc-2.10.1.tar.gz
2020-08-06 18:27:19 [INFO] zsh 5.8: https://www.zsh.org/pub/zsh-5.8.tar.xz
2020-08-06 18:27:38 [ERROR] failed to update entry for ffmpeg
Traceback (most recent call last):
  File "src/update.py", line 222, in uscan
    report = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['uscan', '--safe', '--dehs']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/update.py", line 285, in try_updating_registry_entry
    entry = try_updating_entry(package, existing_entry=existing_entry)
  File "src/update.py", line 251, in try_updating_entry
    latest_version = get_package_version(package)
  File "src/update.py", line 243, in get_package_version
    version = uscan(package, source_dir)
  File "src/update.py", line 226, in uscan
    raise RuntimeError(f"uscan for {package} failed")
RuntimeError: uscan for ffmpeg failed
2020-08-06 18:27:38 [INFO] no updates found
2020-08-06 18:27:38 [ERROR] failed: ffmpeg
